### ISSUE TITLE
Uncaught (in promise) TypeError: Failed

### ISSUE THREAD

**Issue by PatoRoxo** [pishangujeniya/instagram-helper#103]
I used this tool in the past and I had no problems with it. Now I'm trying to use it again and I'm getting some errors. Since I'm not a coder, I can't seem to find what's wrong.
![Sem título](https://github.com/pishangujeniya/instagram-helper/assets/154638951/4ca799f0-7e05-4635-80d9-c0bc84f9bd77)

**Comment by pishangujeniya** [comment]
Sorry, the project doesn't work anymore after the update received in the May, 2020 by Instagram.
We are not clear how the new Instagram work with the chat functionality, so please press star and watch buttons on the repository to make sure that you are stayed updated whenever this project starts working.

> duplicate of #102
