### ISSUE TITLE
not working -- "try tomorrow"

### ISSUE THREAD

**Issue by grossekette** [pishangujeniya/instagram-helper#11]
A great idea, sad it's not working tho

**Comment by pishangujeniya** [comment]
@grossekette 
Thank You for informing,

I just looked that Instagram has updated that API links, and made more secure and restrictions on using such scripts.

So I have started working on a new updated script.

I will close this issue and update the project and release once I am done coding it.

**Comment by shanalikhan** [comment]
@pishangujeniya 
Any idea when it will be completed?
