### ISSUE TITLE
CORS policy

### ISSUE THREAD

**Issue by annalitvin** [pishangujeniya/instagram-helper#13]
has been blocked by CORS policy: Request header field pragma is not allowed by Access-Control-Allow-Headers in preflight response

**Comment by pishangujeniya** [comment]
@annalitvin same and related to #11 
Will be fixed with #11

**Comment by VasiliPupkin256** [comment]
CORS policy is very different from parsing the responses actually. CORS errors means you are trying to fetch JSON by sending AJAX requests from the other domain address.

**Comment by pishangujeniya** [comment]
@VasiliPupkin256 CORS error chrome displays, not only due to CORS error but also if the request is failed with improper parameters or missing (in our case `cursor` parameter is missing).
