### ISSUE TITLE
Uncaught ReferenceError: ActiveXObject is not defined at <anonymous>:22:1

### ISSUE THREAD

**Issue by Ncohen10** [pishangujeniya/instagram-helper#17]
I copy/pasted the InstagramHelperChrome.js code into a notepad file. Then I changed the default opening method for that file to open with chrome. I go to a DM page on instagram.com and paste the InstagramHelperChrome.js code into console. I add:

```
var ig  = new InstagramHelper();
ig.startUnsending("your_chat_thread_Id");
```

Then, I get this error when running.

```
Uncaught ReferenceError: ActiveXObject is not defined at <anonymous>:22:1
```
It corresponds to this line of code I believe:
```
//#region Special Chrome Shortcut Creation
Shell = new ActiveXObject("WScript.Shell");
```

**Comment by pishangujeniya** [comment]
@Ncohen10  you don't need to paste, the InstagramHelperChrome.js file contents into Console tab of browser.

You are doing something wrong.
Please try following steps strictly.

**Comment by Ncohen10** [comment]
Yeah I just missed something in the directions.
