### ISSUE TITLE
Suggestion to make it easier

### ISSUE THREAD

**Issue by ovnx** [pishangujeniya/instagram-helper#18]
An option to make the process easier is to add the following code to the end of instagramhelper.js:

`chatId = window.location.href.split('/')[5]; // Gets the direct message chat id from the url

var ig  = new InstagramHelper();
ig.startUnsending(chatId);`

Then it will automatically start unsending messages for the current DM.

**Comment by pishangujeniya** [comment]
Simply create A pull request
