### ISSUE TITLE
"Some Messages Skipped" constant loop issue

### ISSUE THREAD

**Issue by thejosephwilbur** [pishangujeniya/instagram-helper#20]
Hello - all of a sudden, after the script working for a while to delete messages, it suddenly started giving 'some messages skipped' error. I have tried on another computer, different instagram account, ect. and still the same problem.

**Comment by pishangujeniya** [comment]
Add more longer time of delay as mentioned in Readme file.

Also logout and re-login

**Comment by thejosephwilbur** [comment]
I already tried both of those. Still nothing...

**Comment by itsWEGOO** [comment]
i get the same error, did u find a way to fix it ?

**Comment by pishangujeniya** [comment]
@thejosephwilbur  @itsWEGOO 

- If you want to confirm if any of the messages are skipped or left to delete then you can run the following to get the number of messages that you send which are not yet deleted. 
- ```javascript
    var ig  = new InstagramHelper();
    ig.getAllMessageIds("your_chat_thread_Id");
    ```
- After it says **All Messages fetched, No More messages to fetch**, run the following code to get the number of messages which are yet to delete.
- ```javascript
    console.log(ig.p_itemsIdArray.length);
    ```

Try doing the above steps, and check if any messages are yet to delete or not.

The message "Some Messages Skipped" is displayed, whenever a dm is tried to unsend but Instagram failed to unsend.
