### ISSUE TITLE
Download Instagram DMs

### ISSUE THREAD

**Issue by Deleora** [pishangujeniya/instagram-helper#21]
Hi, I would like to directly scrape all the DM threads from my account. Is it possible to do so using this repository, and if not is there any possibility of adding such feature in the near future? Thanks!

**Comment by pishangujeniya** [comment]
@Deleora  Yes, I can develop this feature.

In fact this feature was already there somewhere around 6 months ago, and no one was using, so I removed it.

I will add it.

**Comment by Deleora** [comment]
Thank you so much for agreeing to add this feature. I really appreciate it. Thanks again!!

**Comment by Deleora** [comment]
Hi @pishangujeniya, I just wanted to know how much time will the development of this feature take?
Thanks.!

**Comment by pishangujeniya** [comment]
@Deleora  Tomorrow, I will complete it and release it.

**Comment by Deleora** [comment]
Wow, that's awesome! 😊

**Comment by pishangujeniya** [comment]
@Deleora  Its done
