### ISSUE TITLE
How to run on Linux and MacOS?

### ISSUE THREAD

**Issue by nisc** [pishangujeniya/instagram-helper#22]
Hey there, thank you for making this open source. Seems very useful. Your description mentions that Windows is required. Is there any technical reason why it would not work with other operating systems that support Python and Chrome?

Which components would I have to adjust to make it compatible with Linux and MacOS, should I decide to work on and send a PR?

(I haven't looked at the code, yet... was hoping that you could clarify this briefly for me and save me some time :-)

Thank you.

**Comment by pishangujeniya** [comment]
# How to run on MacOS and Linux?

![urljdq2sono51sog2gktuc2ckr](https://user-images.githubusercontent.com/25280661/107136041-f16b9c80-6925-11eb-81b5-c5359d35b872.png)

1. Install Chrome Browser
2. Make a temporary directory named as "InstagramHelperChromeData" somewhere in your disk
3. Copy the path to that directory.
4. Now run the chrome browser using the following command line parameters (paste the copied path in below paramters at `YOUR_COPIED_DIRECTORY_PATH`)
5. MacOS command : `/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --disable-web-security --disable-gpu --user-data-dir=YOUR_COPIED_DIRECTORY_PATH`
6. Linux command : `chrome --disable-web-security --disable-gpu --user-data-dir=YOUR_COPIED_DIRECTORY_PATH`
7. Now open [Instagram.com](https://instagram.com) and press `F12` (Developer Tools)
8. Now follow the steps from `README.md` after opening Instagram.com and skip the steps for `InstagramHelperChrome.js` part.

**Comment by nisc** [comment]
Thank you, appreciate the quick response.

**Comment by nowaygraciano** [comment]
> Thank you, appreciate the quick response.

Hello, did this work for you? Somehow I get stuck at step 3-4

**Comment by pishang-marutitech** [comment]
> > Thank you, appreciate the quick response.
> 
> Hello, did this work for you? Somehow I get stuck at step 3-4

Which OS?

**Comment by pishangujeniya** [comment]
> > Thank you, appreciate the quick response.
> 
> Hello, did this work for you? Somehow I get stuck at step 3-4

Which OS you are trying for, Linux or MacOS?

**Comment by nowaygraciano** [comment]
Hello, thanks for the quick reply! I'm on iOS

**Comment by pishangujeniya** [comment]
> Hello, thanks for the quick reply! I'm on MacOS

You need to create a folder somewhere in your laptop disk, and copy the full path to that folder (containing the folder name in the path too) that is what step 2 and 3 are.

And in the step 5 you need to paste that path at the mentioned text `YOUR_COPIED_DIRECTORY_PATH` in the MacOS Command mentioned in the [comment](https://github.com/pishangujeniya/instagram-helper/issues/22#issuecomment-774589015) above

**Comment by nowaygraciano** [comment]
I've tried these but somehow I can't seem to make it work, is there a way of maybe recording this in a tutorial if you don't mind?

**Comment by pishangujeniya** [comment]
> I've tried these but somehow I can't seem to make it work, is there a way of maybe recording this in a tutorial if you don't mind?

Sorry, I don't have Mac, but may be this [answer](https://stackoverflow.com/a/52903727/7703497) can figure you out the way or ask some CS Student to help you out with it.
