### ISSUE TITLE
This file will then generate a Chrome Shortcut on your Desktop with name InstagramHelperChrome

### ISSUE THREAD

**Issue by Bonghui** [pishangujeniya/instagram-helper#24]
Hello my friend.

I was not able to follow the steps, as I was unable to generate a shortcut with the .js file

How do I proceed?

**Comment by Bonghui** [comment]
Should I run the file with a specific program?

**Comment by pishangujeniya** [comment]
https://github.com/pishangujeniya/instagram-helper/issues/25#issuecomment-774955152
