### ISSUE TITLE
ActiveXObject is not defined

### ISSUE THREAD

**Issue by altafhpatel** [pishangujeniya/instagram-helper#25]
ActiveXObject is not defined
try every browser IE, Mozilla, Chrome

**Comment by pishangujeniya** [comment]
@altafhpatel  Windows 10 OS?

**Comment by pishangujeniya** [comment]
Issues #24  and #25 are similar and related to each other. 

Kindly follow the process to handle these errors.

To execute the `InstagramHelperChrome.js` run the following command in `cmd` (Command Prompt) inside the directory where you have the file `InstagramHelperChrome.js`

`wscript.exe InstagramHelperChrome.js`

**Comment by pishangujeniya** [comment]
> ActiveXObject is not defined
> try every browser IE, Mozilla, Chrome

You didn't follow the steps correctly, you tried running the js script in browser, which is not mentioned in the README, you need to create js file in your PC and then double to Run as Microsoft Active Host, not into any Browser.

**Comment by altafhpatel** [comment]
> 
> 
> @altafhpatel Windows 10 OS?

yes i have windows 10 and a shortcut generated on desktop as well (i open it with windows host script) ... also i already configured the path for chrome problem

a shortcut is generated already

**Comment by altafhpatel** [comment]
You are using an unsupported command-line flag: --disable-web-security. Stability and security will suffer

I think the flat for **disable web security** is _not working_

**Comment by pishangujeniya** [comment]
> You are using an unsupported command-line flag: --disable-web-security. Stability and security will suffer
> 
> I think the flat for **disable web security** is _not working_ 

You continue following steps, its just a warning showing that you are using chrom in different mode.

So ignore the warning ⚠️  and continue ahead following steps.

**Comment by Bonghui** [comment]
i really appreciate your help. 

When I double-click in `InstagramHelperChrome.js` nothing happens. 

Just as when I run the command `wscript.exe InstagramHelperChrome.js` in cmd, nothing happens either.

I'm having a hard time finding the reason.

**Comment by pishangujeniya** [comment]
> i really appreciate your help.
> 
> When I double-click in `InstagramHelperChrome.js` nothing happens.
> 
> Just as when I run the command `wscript.exe InstagramHelperChrome.js` in cmd, nothing happens either.
> 
> I'm having a hard time finding the reason. (The difficulty is in step 6, where a shortcut is generated. This is not happening.)
> 
> (yes, the file is on the desktop, windows host is enabled on regedit, i don't have chrome installed on the machine)

You need to first `cd` to that directory where the `.js` files is existing, and thenafter do run `wscript.exe InstagramHelperChrome.js`

**Comment by Bonghui** [comment]
Yes, I navigated to the directory (Desktop).

`c:\Users\My-name\Desktop>wscript.exe InstagramHelperChrome.js`

But nothing happens, the file is executed normally, the shortcut is not created.

**Comment by JustSxm** [comment]
copy paste the code in internet explorer console

**Comment by Deleora** [comment]
> i don't have chrome installed on the machine

@Bonghui you need to have Chrome installed before you can create a custom shortcut

**Comment by pishangujeniya** [comment]
> copy paste the code in internet explorer console

I don't recommend using internet explorer for this purpose
