### ISSUE TITLE
Won't work

### ISSUE THREAD

**Issue by NibbaMakesDespacito2** [pishangujeniya/instagram-helper#26]
Doesn't work. Even after doing exactly what you said, the messages won't start getting deleted. Please give us a more detailed tutorial or something, because I have no idea of what I'm doing wrong. I suspect it might be related with the code of the "InstagramHelperChrome.js" file itself but I don't know. Can you help me? What do you mean by "Change this letter to your folder name which you created in root path of your Windows System drive."? Should I copy the "copyright" section of the "InstagramHelperChrome.js" code too?

**Comment by pishangujeniya** [comment]
@NibbaMakesDespacito2  

Hello, I updated the README and repository with new code and guidance.

I guess you are making mistake where you don't need to run any code of `InstagramHelperChrome.js` into the browser, it just meant to double click the file and which will generate a new Chrome Browser Shortcut on the desktop, and you need to follow the steps on that new Chrome Shortcut.

I suggest trying the latest release version by following the new [README](https://github.com/pishangujeniya/instagram-helper/)
