### ISSUE TITLE
Is it just delete the message or unsend the message?

### ISSUE THREAD

**Issue by menporulporiayalan** [pishangujeniya/instagram-helper#3]
Hi, 

Is this code just delete the dm's or unsending the dm's? Can we do bulk unsend by this code? @pishangujeniya

**Comment by pishangujeniya** [comment]
Unsends the direct messages from both parties according to Instagram

**Comment by pishangujeniya** [comment]
@menporulporiayalan I have updated the code and README.md file.
It now works with latest instagram.com website too.
