### ISSUE TITLE
Error "Try again tomorrow" 

### ISSUE THREAD

**Issue by butterchicken69** [pishangujeniya/instagram-helper#32]
After pasting 
`  var ig  = new InstagramHelper();
  ig.getAllMessageIds("your_chat_thread_Id");`
Error "Try again tomorrow" is shown along with an error code 400
Is this due to the code not being updated to the latest API or am I doing something wrong?
Thanks

**Comment by pishangujeniya** [comment]
Did you replacer "your chat id here"?

**Comment by butterchicken69** [comment]
Damn sorry forgot to do that, it's working now
Thanks man, this is really useful

**Comment by pishangujeniya** [comment]
> Damn sorry forgot to do that, it's working now
> Thanks man, this is really useful

Silly mistakes, better to read the README properly.
