### ISSUE TITLE
Unable to create shortcut

### ISSUE THREAD

**Issue by meikboop** [pishangujeniya/instagram-helper#33]
after downloading the ZIP file and extracting i double clicked InstagramHelperChrome.js but it comes up with a windows host script error saying unable to create shortcut, how do i fix this?

**Comment by pishangujeniya** [comment]
@meikboop 

There might be some cases where you have installed Chrome Browser at some other places, so for those people who have installed Chrome Browser in some other location, they need to manually specify the path to `Chrome.exe` file in the below line of `InstagramHelperChrome.js` file.

- Open the `InstagramHelperChrome.js` file in Notepad and modify the following line

Original Code:
```javascript

var chromeInstalledPath = "C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe"; // Path to the Chrome.exe file installed in your Windows System.

```
To Modify Code:
```javascript

var chromeInstalledPath = "YOUR_PATH_TO_CHROME_EXE_FILE"; // Path to the Chrome.exe file installed in your Windows System.

```
> Note that, the path to Chrome.exe file must be written all single slashes to double slashes as mentioned above in original code.

> Some examples of chrome.exe path
- `C:\Program Files (x86)\Google\Application\chrome.exe`
- `C:\Program Files (x86)\Google\Chrome\Application\chrome.exe`
- `C:\Program Files (x86)\Google\Application\chrome.exe`
- `C:\Program Files\Google\Chrome\Application\chrome.exe`
>  Every slashes should be written twice in code.

Once you got your path correct written in the code save the file, and try executing again.

**Comment by meikboop** [comment]
Hi thank u for replying,
I checked the location of my chrome.exe file but it is the same as the one specified in the original line of code "C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe";
Is there another reason why i am getting an unable to create shortcut error?

**Comment by pishangujeniya** [comment]
@meikboop  Can you please attach the screenshot here?

**Comment by saboo31** [comment]
yeah sure, here is a screenshot of the unable to create shortcut error and a screenshot of the path to chrome.exe 
![2021-05-01](https://user-images.githubusercontent.com/81633373/116782920-c3f54180-aa83-11eb-8145-8a273b187f78.png)
![2021-05-01 (1)](https://user-images.githubusercontent.com/81633373/116782925-ce174000-aa83-11eb-9286-daa52acaa024.png)

**Comment by pishangujeniya** [comment]
@meikboop  Replace line 40 with this line : 

`link = Shell.CreateShortcut("D:" + "\\" + shortCutFileName);`

and then see the ShortCut in D drive

**Comment by meikboop** [comment]
thank you i will try this now, sorry i deleted the screenshots because i want to keep myself anonymous

**Comment by meikboop** [comment]
i replaced line 40 with link = Shell.CreateShortcut("D:" + "\\" + shortCutFileName); but the same error occured, i then tried to replace line 44 with link = Shell.CreateShortcut("D:" + "\\" + shortCutFileName); instead because in the popup with the error line 44 was mentioned but it said see shortcut in desktop but there was no shortcut. I also checked if i had a D drive but i don't have one.
![2021-05-01 (4)](https://user-images.githubusercontent.com/83430342/116783695-2a7c5e80-aa88-11eb-8ae3-8d84f1a51e19.png)
![2021-05-01 (3)](https://user-images.githubusercontent.com/83430342/116783698-2ea87c00-aa88-11eb-8e2a-bd1710219e9b.png)

**Comment by pishangujeniya** [comment]
Then replace that capital D with C in line 40 

> @meikboop Replace line 40 with this line :
> 
> `link = Shell.CreateShortcut("D:" + "\\" + shortCutFileName);`
> 
> and then see the ShortCut in D drive

Replace D with C

**Comment by meikboop** [comment]
i have just replaced D with C but it wont work
![2021-05-01 (5)](https://user-images.githubusercontent.com/83430342/116784072-0a4d9f00-aa8a-11eb-808b-0eb32efed044.png)

**Comment by pishangujeniya** [comment]
@meikboop  Wait 1 hour, I will provide you shortcut file

**Comment by meikboop** [comment]
thank you so much i appreciate it

**Comment by pishangujeniya** [comment]
- Right-Click Desktop
- New >  Shortcut
![image](https://user-images.githubusercontent.com/25280661/118386277-f7170380-b633-11eb-9c8b-43c63bdcb84a.png)

- Paste the following path (including the quotes) (Correct if something is wrong with the path to chrome.exe or your System Drive Letter 'C'

"C:\Program Files\Google\Chrome\Application\chrome.exe" --disable-web-security --disable-gpu --user-data-dir="C:\InstagramHelperTemp"

- Click Next
- Type `InstagramHelperChrome`
- Finish.
