### ISSUE TITLE
TypeError: Cannot read property 'thread' of undefined    

### ISSUE THREAD

**Issue by moestuin** [pishangujeniya/instagram-helper#36]
I made the special chrome browser. Re-did it with the cmd command. 

Afterwards I pasted the instagramhelper.js into the console -> press enter. 

after that I copied   var ig  = new InstagramHelper();
  ig.startUnsending(334235252345624624);  
  
  into the console and pressed enter. 
  
  No matter how many times I retry I get 
  
  TypeError: Cannot read property 'thread' of undefined
    at <anonymous>:370:26
    at async InstagramHelper.startUnsending (<anonymous>:353:13)
    GET https://i.instagram.com/api/v1/direct_v2/threads/3.402823668417103e+38/ 404
startUnsending @ VM39:353
async function (async)
startUnsending @ VM39:429
(anonymous) @ VM47:2
VM39:359 Try again tomorrow
(anonymous) @ VM39:359
Promise.then (async)
startUnsending @ VM39:357
async function (async)
startUnsending @ VM39:429
(anonymous) @ VM47:2
VM39:369 getting messages...

**Comment by pishangujeniya** [comment]
Thread id should be passed in quotes,
ig.startUnsending("334235252345624624");

**Comment by moestuin** [comment]
O boy, do i feel stupid now. I guess I'm really showing that im a c# developer and not JS!

It works flawlessly.
