### ISSUE TITLE
Delete recieved messages 

### ISSUE THREAD

**Issue by omaniboy** [pishangujeniya/instagram-helper#37]
I tried it and sent messages were deleted, but is there a way to delete both send and recieved messages in direct medsage on instagram ?

**Comment by pishangujeniya** [comment]
@omaniboy  Need to look at it.

**Comment by omaniboy** [comment]
Sure take your time, thanks.

**Comment by pishangujeniya** [comment]
@omaniboy  Instagram itself doesn't support deleting the messages received, so our script can not.
