### ISSUE TITLE
Error whenever I try to execute it

### ISSUE THREAD

**Issue by ibliscode** [pishangujeniya/instagram-helper#4]
I'm probably just really stupid and I'm not doing it right, but whenever I try to execute the code, I get this error:

VM419:1 Uncaught ReferenceError: InstagramHelper is not defined
    at <anonymous>:1:17

Yes, I uninstalled the plugin.

If you could be so kind, could you provide a more detailed instruction for someone as dumb as me? ;)

**Comment by daastans** [comment]
404 , Try again Tommorow error. Seems Like you didnt tested it enough before rolling out OR this repo is not useful anymore i guess.

**Comment by pishangujeniya** [comment]
@ibliscode , I need to update the README.md for guidance, as the instagram has changed some of code, and I have updated the script and its working and tested.

I will update the README.md file soon and will inform you.

@daastans  Its working and tested

**Comment by pishangujeniya** [comment]
@ibliscode @daastans 

Follow the updated [README.MD](https://github.com/pishangujeniya/instagram-helper/blob/master/README.md)

**Comment by pishangujeniya** [comment]
> 404, Try again Tomorrow error. Seems Like you didnt tested it enough before rolling out OR this repo is not useful anymore i guess.

I have fixed that issue of *try again tomorrow*

If you can read the [README.md](https://github.com/pishangujeniya/instagram-helper/blob/master/README.md)

I have mentioned that there is limit in unsending the direct messages per session by Instagram, so previous code was instantly very fastly deleting all the messages and hitting the limit, so now with the latest code it unsends like human behaviour, very few with some interval of delay, and I have not yet got the error of *Try Again Tomorrow* then after.

**Comment by ibliscode** [comment]
Thank you so much!

However, I now have a new error:

VM104:1 Uncaught ReferenceError: InstagramHelper is not defined
    at <anonymous>:1:11

**Comment by pishangujeniya** [comment]
> 
> 
> Thank you so much!
> 
> However, I now have a new error:
> 
> VM104:1 Uncaught ReferenceError: InstagramHelper is not defined
> at :1:11

have you first copied the source code of InstagramHelper.js file contents to the F12 Console first?
after copying you need to run those commands.

**Comment by ibliscode** [comment]
My bad, chief.

I tried that and it worked until I started getting the "try again tomorrow" error.

**Comment by pishangujeniya** [comment]
> My bad, chief.
> 
> I tried that and it worked until I started getting the "try again tomorrow" error.

I guess you are not running the latest code.

You should try running the latest InstagramHelper.js file from master branch.

You can provide your TeamViewer details on my email, i can help you a demo with it.

**Comment by ibliscode** [comment]
I'll try to find a time for that!  Thanks so much for your help!

**Comment by pishangujeniya** [comment]
I have updated to latest code which has continuous deleting of messages functionality.
A better and faster way to start deleting messages.

### Previous Flow:
- It was first getting all the messages since the chat initiated and then starts deleting.

### Current Flow: 
- It will get some chunk of messages which are needed to delete, and then start deleting and then repeat for next chunk.

If you can read the README.md
