### ISSUE TITLE
The instagram unsend script isnt working 

### ISSUE THREAD

**Issue by divya253** [pishangujeniya/instagram-helper#41]
whenever i put the code its showing error
![Screenshot (4673)](https://user-images.githubusercontent.com/85884322/121901273-df6e9000-cd43-11eb-91d8-584766160dd4.png)
i really want to unsend my messages as soon as possible

thank you

**Comment by pishangujeniya** [comment]
Yes, this issue is occurring recently, due to updates by Instagram

Will try to fix in couple of days

**Comment by pishangujeniya** [comment]
- Follow the initial steps

After following Initial steps of Readme

- Open any chat and then see the link should be such as (https://www.instagram.com/direct/t/xxxx)
- Note and copy the last long numerical digits from link to some notepad.
- Those digits is your chat thread Id.
- Now Copy the `InstagramHelper.js` file contents and paste it in `Console` tab
- Copy Paste the following code in Console and Hit Enter
- ```javascript
    var ig  = new InstagramHelper();
    ig.startUnsending("your_chat_thread_Id");
    ```

Here replace the words `your_chat_thread_Id` with your chat id which is in the link when you open the chat.

You didn't read the [Readme](https://pishangujeniya.github.io/instagram-helper/) properly.
Follow the steps properly it will work.
I tested and confirmed

**Comment by divya253** [comment]
> * Follow the initial steps
> 
> After following Initial steps of Readme
> 
> * Open any chat and then see the link should be such as (https://www.instagram.com/direct/t/xxxx)
> * Note and copy the last long numerical digits from link to some notepad.
> * Those digits is your chat thread Id.
> * Now Copy the `InstagramHelper.js` file contents and paste it in `Console` tab
> * Copy Paste the following code in Console and Hit Enter
> * ```js
>     var ig  = new InstagramHelper();
>     ig.startUnsending("your_chat_thread_Id");
>   ```
> 
> Here replace the words `your_chat_thread_Id` with your chat id which is in the link when you open the chat.
> 
> You didn't read the [Readme](https://pishangujeniya.github.io/instagram-helper/) properly.
> Follow the steps properly it will work.
> I tested and confirmed

i followed this exactly as u said and it still isnt working

**Comment by pishangujeniya** [comment]
> > * Follow the initial steps
> > 
> > After following Initial steps of Readme
> > 
> > * Open any chat and then see the link should be such as (https://www.instagram.com/direct/t/xxxx)
> > * Note and copy the last long numerical digits from link to some notepad.
> > * Those digits is your chat thread Id.
> > * Now Copy the `InstagramHelper.js` file contents and paste it in `Console` tab
> > * Copy Paste the following code in Console and Hit Enter
> > * ```js
> >     var ig  = new InstagramHelper();
> >     ig.startUnsending("your_chat_thread_Id");
> >   ```
> > 
> > Here replace the words `your_chat_thread_Id` with your chat id which is in the link when you open the chat.
> > You didn't read the [Readme](https://pishangujeniya.github.io/instagram-helper/) properly.
> > Follow the steps properly it will work.
> > I tested and confirmed
> 
> i followed this exactly as u said and it still isnt working

Screenshots itself says that you didn't replace the chat id.

Please do read the properly  very carefully, you will know you are not putting the chat id numbers while running th code

**Comment by divya253** [comment]
i did it just now and it says that it has been blocked by cors policy 
i put the chat thread id right now

**Comment by pishangujeniya** [comment]
> Here replace the words `your_chat_thread_Id` with your chat id which is in the link when you open the chat.

This thing you missed

**Comment by pishangujeniya** [comment]
> i did it just now and it says that it has been blocked by cors policy
> i put the chat thread id right now

You didn't followed Initial steps

**Comment by divya253** [comment]
am i putting the code wrong? first i have to put the long code and then press enter or put the other code in the next line?

**Comment by pishangujeniya** [comment]
https://github.com/pishangujeniya/instagram-helper#initial-steps

**Comment by divya253** [comment]
ah okay i'll try it once more

**Comment by pishangujeniya** [comment]
You might be using the chrome browser which you daily use, you need to use special browser that is generated by the Initial Steps

**Comment by divya253** [comment]
altho do i have to press enter after entering the first code?

**Comment by pishangujeniya** [comment]
> https://github.com/pishangujeniya/instagram-helper#initial-steps

Follow this, it will generate a new chrome icon on desktop in which you need to proceed further.

**Comment by divya253** [comment]
still isn't working where am i going wrong?

**Comment by pishangujeniya** [comment]
> still isn't working where am i going wrong?

  var ig  = new InstagramHelper();
  ig.startUnsending("your_chat_thread_Id");


Did you replace with you chat number ids?

**Comment by divya253** [comment]
yes i did

**Comment by pishangujeniya** [comment]
Screenshot of error attach please

> yes i did

**Comment by divya253** [comment]
okay one second
\

**Comment by pishangujeniya** [comment]
You need to use the new chrome shortcut generated using  this file https://pishangujeniya.github.io/instagram-helper/InstagramHelperChrome.js


Save the link by opening and then ctrl+s and save the file somewhere

And double click on that file.

Now it will generate a shortcut on desktop, use that shortcut to open chrome.

**Comment by divya253** [comment]
um it shows red something but it also says deleting so is it deleting?

**Comment by pishangujeniya** [comment]
> um it shows red something but it also says deleting so is it deleting?

You can confirm after everything is done refresh the page and open the chat and then follow

https://github.com/pishangujeniya/instagram-helper#-how-to-get-exported-all-messages

**Comment by pishangujeniya** [comment]
Do hit star the repository and share the link to your networks, if you are satisfied with it.

**Comment by divya253** [comment]
it logged me out of my account saying that we noticed some fishy activity

**Comment by pishangujeniya** [comment]
Try again after 45 mins,
It happens normally.

**Comment by pishangujeniya** [comment]
You might have done repeatedly wrong attempts so.

**Comment by divya253** [comment]
ah okay

**Comment by pishangujeniya** [comment]
What was the red error you getting?

If you were getting CORS error you did wrong steps, thats why it logged you out.

**Comment by divya253** [comment]
i got the cors error earlier not after it started deleting messages

**Comment by pishangujeniya** [comment]
> i got the cors error earlier not after it started deleting messages

That means you using the new special browser shortcut generated on the desktop?

**Comment by divya253** [comment]
yes
