### ISSUE TITLE
"access to fetch" error

### ISSUE THREAD

**Issue by johnfedet** [pishangujeniya/instagram-helper#42]
![image](https://user-images.githubusercontent.com/86513200/123506639-1e40f780-d61a-11eb-9228-e52bf00b7541.png)

how do I fix this?

**Comment by pishangujeniya** [comment]
Need to use that special Chrome Browser

Not the normal browser that you use daily.

**Comment by johnfedet** [comment]
I did, however when i run the chrome browser it brings me to some opening json file website

**Comment by pishangujeniya** [comment]
@johnfedet  you going wrong way,

You need to use the shortcut which is created on your desktop using the Instagram Chrome Helper file.

Please read the initial steps first.

**Comment by johnfedet** [comment]
I did, It tells me to select a file to open with. Which do I choose?

**Comment by pishangujeniya** [comment]
> I did, It tells me to select a file to open with. Which do I choose?


Initial Steps
Install Chrome Browser
Open https://github.com/pishangujeniya/instagram-helper/releases/
Download latest release version (Source Code zip) and extract to desktop.
Double click InstagramHelperChrome.js from the extracted folder. (This js file is not to be run into browser or browser console, only need to double click and run with Windows Active Host)
That will then generate a Chrome Shortcut on your Desktop with name InstagramHelperChrome
Open that Special Chrome Browser using that shortcut.

**Comment by pishangujeniya** [comment]
> I did, It tells me to select a file to open with. Which do I choose?

You need to read the REaDME properly, every line, even if it doesn't relate to your need.

**Comment by johnfedet** [comment]
basically, I opened InstagramHelperChrome.js, the chrome thing was created, when I click on it though, it takes me to file:///C:/Users/admin/Desktop/InstagramHelperDataViewer.html. After that I go to instagram and it displays the same error code

**Comment by pishangujeniya** [comment]
When you open that new chrome icon created on desktop with name `InstagramHelperChrome`

Double click that chrome, and open instagram.com in that new chrome which will ask you to login, and then follow the steps

**Comment by johnfedet** [comment]
I fixed it and ran the script for a couple hours, but now im stuck on getting messages and it stopped deleting them after a while

**Comment by johnfedet** [comment]
![image](https://user-images.githubusercontent.com/86513200/123522362-a999a780-d671-11eb-87c2-52a6c48b31f9.png)

I also get this

**Comment by johnfedet** [comment]
![image](https://user-images.githubusercontent.com/86513200/123522373-ba4a1d80-d671-11eb-96ec-74df4c5641ed.png)
and this, it isnt deleting any of my messages at all
