### ISSUE TITLE
July 23/not working

### ISSUE THREAD

**Issue by clefaux** [pishangujeniya/instagram-helper#43]
After each use attempt now,I get :

Uncaught ReferenceError: InstagramHelper is not defined
    at <anonymous>:1:11

**Comment by clefaux** [comment]
this is after multiple login/logouts and deleting/re downloading the browser

**Comment by pishangujeniya** [comment]
@clefaux You are not following proper guidelines as per mentioned in README, that is the reason this error coming.

Please read every steps very carefully and follow slowly, every steps with proper reading the details mentioned.

**Comment by clefaux** [comment]
ok, I did, and now I get a javascript error. which has never happened.

Uncaught ReferenceError: javascript is not defined
    at <anonymous>:645:1
    
    and yes I followed the steps and typed everything correctly. multiple times.

**Comment by pishangujeniya** [comment]
> ok, I did, and now I get a javascript error. which has never happened.
> 
> Uncaught ReferenceError: javascript is not defined
> at :645:1
> 
> and yes I followed the steps and typed everything correctly. multiple times.

To be honest, clearly the error describes that, you either understood something wrong while reading the README, or you might have not followed the steps correctly.

**Comment by clefaux** [comment]
😂🥲 right. thanks.
