### ISSUE TITLE
Error 'Try again tomorrow' despite doing all steps correctly. 

### ISSUE THREAD

**Issue by Chillax4Nothing** [pishangujeniya/instagram-helper#44]
So, I've tried all the steps correctly, in exact order. Downloaded the given latest zip file, extracted it, it made a google chrome in my desktop. I've opened it, login my instagram and I went to it developer console (F12) and pasted the Instagramhelper.js file source code in it and copied the following 2 line code and added the message id in the place and run the program, it says "Try again tomorrow". Why? 
![image](https://user-images.githubusercontent.com/70951159/127671787-0dd9c111-a140-4981-a75a-c9f2fe3b4505.png)

**Comment by Chillax4Nothing** [comment]
Edit: I've tried the delay thing too, 3500, 4500, 5500, 6500, still didn't work.

**Comment by pishangujeniya** [comment]
> So, I've tried all the steps correctly, in exact order. Downloaded the given latest zip file, extracted it, it made a google chrome in my desktop. I've opened it, login my instagram and I went to it developer console (F12) and pasted the Instagramhelper.js file source code in it and copied the following 2 line code and added the message id in the place and run the program, it says "Try again tomorrow". Why?
> ![image](https://user-images.githubusercontent.com/70951159/127671787-0dd9c111-a140-4981-a75a-c9f2fe3b4505.png)

You need to only pass the threadId in startUnsending

You passed whole link, only the number after t/

**Comment by Chillax4Nothing** [comment]
You know what? 

I love you, thanks for the speed reply and your help.
