### ISSUE TITLE
couldn't install chrome

### ISSUE THREAD

**Issue by IBRamal** [pishangujeniya/instagram-helper#46]
after the shortcut was created, i clicked on it, and selected chrome.exe, then it threw an error (couldn't install) 
![error](https://user-images.githubusercontent.com/88318222/131109915-a2440985-9443-4dfc-a14c-1eb5ad9f204c.png)

**Comment by pishangujeniya** [comment]
https://github.com/pishangujeniya/instagram-helper/blob/b83dd03897c5014d9bfe995f04094dbb7dd1e7d7/InstagramHelperChrome.js#L29

`var systemDriveLetter = "C"; // Change this letter to your Windows System Drive Letter.`

Change the above letter "C" to "D" or some other Drive letter.

Then delete the shortcut created previously, and execute the file again, and try to open the Chrome Again.

**Comment by IBRamal** [comment]
Thank you for your response.
Unfortunately, my drive letter is C, and it still throws an error. Could you please recommend another solution? Thank you for your patience!

**Comment by pishangujeniya** [comment]
> Thank you for your response.
> Unfortunately, my drive letter is C, and it still throws an error. Could you please recommend another solution? Thank you for your patience!

Instead of C Letter, put the Path to your Desktop Folder and then try

**Comment by pishangujeniya** [comment]
@IBRamal  It is fixed in version 2.1
