### ISSUE TITLE
Multiple errors (not even 1 message unsent)

### ISSUE THREAD

**Issue by geekyanky** [pishangujeniya/instagram-helper#47]
**Describe the bug**
I am getting multiple errors including "try tomorrow" and "thread not defined" multiple times, no message unsent

I have followed all steps diligently and also closed chrome ink then relogged in, even made my account public also tried changing the delay to 6500 and even 10500 but didn't work

How can I resolve this issue?

**Comment by pishangujeniya** [comment]
- No need to make your account public

Check this https://github.com/pishangujeniya/instagram-helper/issues/36#issuecomment-833928380

**Comment by geekyanky** [comment]
Great, it started working now. But it gets stuck at "all messages fetched, no more messages to fetch" and does not delete any messages.

**Comment by pishangujeniya** [comment]
> Great, it started working now. But it gets stuck at "all messages fetched, no more messages to fetch" and does not delete any messages.

Didn't it show you a message saying that, _deleting messages_

**Comment by geekyanky** [comment]
No it gets stuck after saying 168 messages and "all messages fetched, no more messages to fetch". Screen shot attached. Pls advice.

![image](https://user-images.githubusercontent.com/85503901/131263763-33feca29-3938-468f-9d4b-711936cb5c07.png)

**Comment by pishangujeniya** [comment]
Why are you running `ig.getAll..`
You need to run `ig.startUns...` check readme properly.

**Comment by geekyanky** [comment]
The issue seems to have resolved since I could delete both messages and media. 

So just for record-
1. Insert the chat ID that you want to delete the chat for inside the double quotes
2. Stay in the chat glance window without clicking the chat when actually running the code (get the chat ID beforehand)

Other tips-
The console should not show any error in red before you start; for this purpose, log out, clear complete history for all time (in the chrome Instagram helper shortcut, then log in again)

Thank you @pishangujeniya for your code and efforts, nothing similar to this actually exists out there and I will be forever grateful to you for making this project and it being open-source.

**Comment by pishangujeniya** [comment]
Glad to hear that it helped you.

It would be better if you can donate if it saved you a lot of time.
