### ISSUE TITLE
Unable to save shortcut

### ISSUE THREAD

**Issue by SirRonaldP** [pishangujeniya/instagram-helper#48]
---------------------------
Windows Script Host
---------------------------
Script:	C:\Users\layer\OneDrive\שולחן העבודה\instagram-helper-2.0\InstagramHelperChrome.js
Line:	44
Char:	1
Error:	Unable to save shortcut "C:\Users\layer\OneDrive\????? ??????\InstagramHelperChrome.lnk".
Code:	8007007B
Source: 	WshShortcut.Save

---------------------------
OK   
---------------------------

I can't open the InstagramHelperChrome.js

**Comment by pishangujeniya** [comment]
@SirRonaldP  Fixed in new version release 2.1
