### ISSUE TITLE
Shows error

### ISSUE THREAD

**Issue by fredrecnroll** [pishangujeniya/instagram-helper#50]
**Describe the bug**
Before I even copy paste the code on console, it shows many errors. Attaching a photo for better understanding. Even when I do try to run the code, nothing is deleted and the errors continue to come. Please resolve if possible. 
![16320883219455555395842387758700](https://user-images.githubusercontent.com/91033773/133944204-1dee1025-692c-4d1e-a8c5-e2c9064c278b.jpg)

**Comment by pishangujeniya** [comment]
You didn't read the Readme properly.

See first point of FAQ

Getting errors displayed in console while running the code

There might be some errors related to Instagram site, not every error displayed on console are from our script.

**Comment by fredrecnroll** [comment]
I did read the readme and followed all the instructions correctly. Also followed what was said in the FAQ, re-logged in a number of times but the error persisted for some reason. I understand that it isn't a problem with your code, but just wanted to ask if there was any other way to go around the problem. If there is one, then pls do tell :p Thanks a lot!!! :D

**Comment by pishangujeniya** [comment]
Ignore the errors
