### ISSUE TITLE
Skip x number of recent messages

### ISSUE THREAD

**Issue by andna** [pishangujeniya/instagram-helper#53]
**Is your feature request related to a problem? Please describe.**
I don't like that messages are visibly seen to be deleted by the receiver since the deletion starts from last to first.

**Describe the solution you'd like**
The deleter would start erasing the first message ever sent, then second, third... etc and finally the last one

**Describe alternatives you've considered**
If not possible... maybe a flag for not deletting the last X messages, and only delete all the past ones... so either this last ones can be manually deleted or after the whole process

**Additional context**

**Comment by pishangujeniya** [comment]
@andna  Check latest release
