### ISSUE TITLE
Delete from the xth message from the last, then the oldest and the oldest

### ISSUE THREAD

**Issue by Hasan-Mahdi** [pishangujeniya/instagram-helper#54]
Hello, thank you for this wonderful script, but I do not want the conversation to be deleted from the last message to the beginning, but from the 100th message and above, meaning it starts from the 100th message from the last, then the oldest, and the oldest.
Can i do this thing?
thanks ❤

**Comment by pishangujeniya** [comment]
@Hasan-Mahdi  Check latest release
