### ISSUE TITLE
Open that Special Chrome Browser using that shortcut. (Ignore the flag that says You are using an unsupported comman-line flag: --disable-web-security. Stability and security will suffer) (This flag is shown because we will be mimicking the automation process of Sending Request to Instagram using Chrome

### ISSUE THREAD

**Issue by Visheshg08** [pishangujeniya/instagram-helper#55]
open which special chrome browser using the shortcut(InstagramHelperChrome).
I'm stuck on this step. Please help Asap

**Comment by pishangujeniya** [comment]
Double click InstagramHelperChrome.vbs from the extracted folder.

This step would have created a shortcut of special google chrome on your desktop.

**Comment by pishangujeniya** [comment]
Follow initial steps properly.

https://github.com/pishangujeniya/instagram-helper#initial-steps
