### ISSUE TITLE
Multiple errors while deleting

### ISSUE THREAD

**Issue by nidonidocom** [pishangujeniya/instagram-helper#56]
**Describe the bug**
While trying to delete messages im getting multiple eroors. Messages do not start to delete at all.
screenshot provided

![image](https://user-images.githubusercontent.com/62544302/140556980-0691ebdf-07ff-45c4-bd59-0f7bcdc88b37.png)

**Comment by pishangujeniya** [comment]
You need to use the Special Chrome Browser mentioned in the https://github.com/pishangujeniya/instagram-helper#initial-steps Initial Steps
