### ISSUE TITLE
not able to paste  InstagramHelper.js content in console tab

### ISSUE THREAD

**Issue by mohinityagi** [pishangujeniya/instagram-helper#58]
InstagramHelper.js content not being pasted in console tab what to do if you don;t have any problem then can you give a video which is based on how to unsend all messages on instagram at once plzzzzzzz

**Comment by pishangujeniya** [comment]
@mohinityagi May be you have not even copied so you are not able to paste it.

Try copying and then pasting in notepad, if it works then pasting in console should also work.
