### ISSUE TITLE
Getting 429 Error

### ISSUE THREAD

**Issue by faiq955** [pishangujeniya/instagram-helper#6]
The script run fine for a day. I had messages of a year, the srcript run fine for a day and unsent messages. But now it is giving 429 error. What could be the issue, instagram is blocking requests. What is the fix for this. Please help.

**Comment by pishangujeniya** [comment]
@faiq955 Yes, you are right, whenever you get this 429 Error. Skip for a day, and logout and re-login after day, and it will start working fine.

**Comment by faiq955** [comment]
So I have waited a day and now script runs fine, no 429 requests. Anyone who has a lot of messages (in thousands) which he wants to unsend, if you get a 429 error after the script is run for a long time (in my case a whole day) then wait for a day. 
Basically Instagram API has a rate limit to how many requests a third party can make in a day. Once the rate limit is up, you will get a 429 error. So, You have to wait a day for Instagram request limit to reset and then try again.

**Comment by pishangujeniya** [comment]
> 
> 
> So I have waited a day and now script runs fine, no 429 requests. Anyone who has a lot of messages (in thousands) which he wants to unsend, if you get a 429 error after the script is run for a long time (in my case a whole day) then wait for a day.
> Basically Instagram API has a rate limit to how many requests a third party can make in a day. Once the rate limit is up, you will get a 429 error. So, You have to wait a day for Instagram request limit to reset and then try again.

Thanks for the explanation. 👌
