### ISSUE TITLE
cannot read properties of undefined (reading 'thread')

### ISSUE THREAD

**Issue by kayaea** [pishangujeniya/instagram-helper#60]
Hİ,
The console has been saying getting messages... (and some errors ( i assume) in red)  for 20mins for a chat that includes 10 messages (was trying if it worked).
![Screenshot 2021-12-12 185620](https://user-images.githubusercontent.com/96015274/145719501-922b55f5-bf6a-42e3-b43b-5faabbbc7b4b.png)

**Comment by kayaea** [comment]
It happens again. Can you fix it... please...

**Comment by pishangujeniya** [comment]
- Make sure you are using Google Chrome Latest Updated Browser
- Make sure you are following proper steps and using latest files [release](https://github.com/pishangujeniya/instagram-helper/releases)

**Comment by pishangujeniya** [comment]
Closing the issue due to no response for longer time.
