### ISSUE TITLE
Giving error 

### ISSUE THREAD

**Issue by Krishrat** [pishangujeniya/instagram-helper#63]
<thread_id>:1 Access to fetch at 'https://i.instagram.com/api/v1/direct_v2/threads/<thread_id here>/' from origin 'https://www.instagram.com' has been blocked by CORS policy: Request header field pragma is not allowed by Access-Control-Allow-Headers in preflight response.

It is giving this error after following all steps carefully.
Please help
![error](https://user-images.githubusercontent.com/55632362/148541152-e8083e4b-d031-48ee-b4b2-8797a17731a3.JPG)

**Comment by pishangujeniya** [comment]
You need to follow the initial steps all first.

Need to use that special chrome browser as mentioned in Readme initial steps
