### ISSUE TITLE
Saying it is Deleting Msgs but it isn't 

### ISSUE THREAD

**Issue by DrAhmed12** [pishangujeniya/instagram-helper#65]
Hello I'm using Version 2.3 I do everything as mentioned in the blog (Downloading,Making a file,copying the number,etc) and when i post everything in the console it says deleting Msgs but everything is still there and after 2 Mins it says all msgs are deleted but they are all there and i will attach the console down 
[Bug.txt](https://github.com/pishangujeniya/instagram-helper/files/7965316/Bug.txt) PLs help and thank you

**Comment by pishangujeniya** [comment]
You should always use the latest version.

There seems no such major issue in the script.

Try using latest version, and with proper steps following from Readme.
