### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'thread')

### ISSUE THREAD

**Issue by sahin-guclu** [pishangujeniya/instagram-helper#66]
Hello so I have used Instagram Helper last few day it was working fine, but today I got an error you can see them with the screenshot I have attached.

![image](https://user-images.githubusercontent.com/99397645/153386805-30d05480-fa19-4441-8304-af5ed7482f76.png)

 I have followed all the initial steps properly and when I used this scripts 3 days back everything went smooth without any error. But I have getting this last 2 days today and yesterday.

**Comment by sahin-guclu** [comment]
Update: I have tried the delay thing too 4500, 5500, 10500, still didn't work.
![image](https://user-images.githubusercontent.com/99397645/153543307-c8b1acfb-ae3d-4034-8704-34abb91bd367.png)

**Comment by pishangujeniya** [comment]
You are doing perfect steps, but I guess, the instagram people have changed the response now.
I need to solve it and will release a new version after 24 hours.

**Comment by Houss30** [comment]
Hi ! I just find out our solution and this is great ! Thanks a lot
Unfortunately I got the same problem so I couldn't use it, is there any hope this solution will work again?
Thanks

**Comment by pishangujeniya** [comment]
@sahin-guclu @Houss30  Its fixed in version [Release 2.5](https://github.com/pishangujeniya/instagram-helper/releases/tag/2.5)

**Comment by Houss30** [comment]
> @sahin-guclu @Houss30 Its fixed in version [Release 2.5](https://github.com/pishangujeniya/instagram-helper/releases/tag/2.5)

Thanks a lot !

**Comment by LucasNH** [comment]
Hi, thank you for keeping this up-to-date, it's great! However even with version 2.5, I get this same error after getting about 1300 messages. Is this a limit on Instagram's side, or is it an issue on my end? Thanks!

**Comment by rvv-r** [comment]
Hi, I've got the same error in the latest release. I've double checked each steps of installation, but it seems like the problem is coming from instagram. @pishangujeniya

**Comment by pishangujeniya** [comment]
@rvv-r I don't think so latest version has any problems, I am able to unsend successfully.
