### ISSUE TITLE
VM34:1 Uncaught ReferenceError: InstagramHelper is not defined     at <anonymous>:1:13

### ISSUE THREAD

**Issue by hmilan8** [pishangujeniya/instagram-helper#67]
trying to run the script and just keep getting the same error console message.

VM34:1 Uncaught ReferenceError: InstagramHelper is not defined
    at <anonymous>:1:13

**Comment by pishangujeniya** [comment]
You have not followed the Steps mentioned in Readme Properly.
Kindly follow the steps properly.
