### ISSUE TITLE
Websocket connection to 'wss://edge-chat.instagram.com/ Error

### ISSUE THREAD

**Issue by williamnamgyal** [pishangujeniya/instagram-helper#68]
This script has been working for the past couple days, but today some reason it is saying 
![image](https://user-images.githubusercontent.com/64612607/154812666-1a7e2e00-28c2-4c58-8a57-70afd35cd185.png)
the error is "afd6b72d7093.js:17 WebSocket connection to 'wss://edge-chat.instagram.com/chat' failed: Close received after close"
And then when I paste in the script like i usually do and then define the variable and then start running it, it gets this error message:
![image](https://user-images.githubusercontent.com/64612607/154812716-f2bde0ae-d744-41d2-9593-d180277f0311.png)

**Comment by pishangujeniya** [comment]
Fixed in [Release 2.5](https://github.com/pishangujeniya/instagram-helper/releases/tag/2.5)
