### ISSUE TITLE
Cant create the shortcut

### ISSUE THREAD

**Issue by Malik-sh** [pishangujeniya/instagram-helper#69]
**Describe the bug**

Hi Team, I can not download the shortcut from the VBS file. WHen I double click, my mac asks me to decide which application to open the VBS file from. 

Any help?

Best, 
Shehroz

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Browser [e.g. chrome]

**Additional context**

**Comment by pishangujeniya** [comment]
Please read the Readme properly, it has mentioned that if you are a mac or linux user, then this shortcut releated process is needed to be skipped and need to follow other steps metioned in the readme.

**Comment by pishangujeniya** [comment]
How to run on Mac or Linux OS
https://github.com/pishangujeniya/instagram-helper/issues/22#issuecomment-774589015
