### ISSUE TITLE
Error "Try again tomorrow" when running code. 

### ISSUE THREAD

**Issue by APexams01** [pishangujeniya/instagram-helper#7]
I followed the steps exactly and got a "Try again tomorrow" error alongside error codes 400 and 200. Tried to log out and back in but that did not work either.

**Comment by pishangujeniya** [comment]
@APexams01  After which step do you get this error "Try again tomorrow" ?

**Comment by APexams01** [comment]
I got it when I ran the last line of code that was given. ig.deleteAllMessages("your_chat_thread_Id");

**Comment by pishangujeniya** [comment]
> 
> 
> I got it when I ran the last line of code that was given. ig.deleteAllMessages("your_chat_thread_Id");

I am making and updating the code now, which will continuous delete the messages and update the steps and readme file.
Will update the repository in an hour and also will comment  here to notify.

**Comment by pishangujeniya** [comment]
@APexams01  I have updated the repository and code, Now read the README.md and use the latest code for the file.

**Comment by APexams01** [comment]
Thank you, I will take a look
