### ISSUE TITLE
WHY IS "TRY AGAIN TOMORROW" AND "GETTING MESSAGES" BEING SHOWN AT THE SAME TIME? HOW TO FIX THIS?

### ISSUE THREAD

**Issue by kermitbbg** [pishangujeniya/instagram-helper#70]
I AM BEING SHOWN "TRY AGAIN TOMORROW" AND "GETTING MESSAGES" AT THE SAME TIME WHEN I TRY TO UNSEND MESSAGE. I CLOSED AND THEN DID AGAIN BUT STILL IT IS THE SAME. I am even being shown the following attached images
![before ex](https://user-images.githubusercontent.com/101860058/158996690-588c5b3d-9899-44fb-8760-0dad0fc7cf19.JPG)
![22](https://user-images.githubusercontent.com/101860058/158996731-3f561519-4392-4f73-82cc-bce6d0504cb9.JPG)

**Comment by pishangujeniya** [comment]
Use latest version from releases

And then try again.

**Comment by kermitbbg** [comment]
i did. i used the latest 2.5 source code (zip)

**Comment by pishangujeniya** [comment]
You need to write thread id in double quotes

"123455xxxxxxx"

**Comment by kermitbbg** [comment]
ohhhhh
ok 
so for example var ig  = new InstagramHelper();
  ig.startUnsending(“340282366841710300949128114326500327139”,5500);
this way right?

**Comment by pishangujeniya** [comment]
> ohhhhh
> ok 
> so for example var ig  = new InstagramHelper();
>   ig.startUnsending(“340282366841710300949128114326500327139”,5500);
> this way right?
> 

Also no need to write ,5500 after thread id.

**Comment by kermitbbg** [comment]
ok so what i do write instead of "5500"

**Comment by kermitbbg** [comment]
i am also being shown "try again tomorrow" and "getting messages" both at the same time. and it is taking so much of time to get the message. normally how long do i need to wait in order for it to get deleted?

**Comment by pishangujeniya** [comment]
Copy Paste the following code in Console and Hit Enter (the number 10 after chat thread id is in the code after comma is for skipping recently sent 10 messages from unsending, you can change it to whatever number you want to skip those number of recently you send messages from unsending).

``` 
var ig = new InstagramHelper(); ig.startUnsending("your_chat_thread_Id",10);

```



See instead of 10 your can write any number which is greater than 3, it means recently sent last 10 messages will not be deleted.

**Comment by kermitbbg** [comment]
![see](https://user-images.githubusercontent.com/101860058/159002884-8e9319eb-e650-49e7-8adf-10a611076a93.JPG)
i tried again and this is what it is showing

**Comment by pishangujeniya** [comment]
I feel the double quotes are not proper.

**Comment by kermitbbg** [comment]
> Copy Paste the following code in Console and Hit Enter (the number 10 after chat thread id is in the code after comma is for skipping recently sent 10 messages from unsending, you can change it to whatever number you want to skip those number of recently you send messages from unsending).
> 
> ```
> var ig = new InstagramHelper(); ig.startUnsending("your_chat_thread_Id",10);
> ```
> 
> See instead of 10 your can write any number which is greater than 3, it means recently sent last 10 messages will not be deleted.

ok will do that

**Comment by pishangujeniya** [comment]
Copy from the above mentioned comment, and don't delete the quotes, simply replace with the your chat thread id.

**Comment by kermitbbg** [comment]
> I feel the double quotes are not proper.



> Copy from the above mentioned comment, and don't delete the quotes, simply replace with the your chat thread id.

ok will try now

**Comment by kermitbbg** [comment]
OHH MY GOD. THANK YOU SO MUCH. ITS WORKING NOW. MY GOODNESS. GOD BLESS YOU WITH ALL THE SUCCESS IN LIFE

**Comment by pishangujeniya** [comment]
You can press close issue now.

**Comment by pishangujeniya** [comment]
If it helped you, then do donate for a coffee. 🥰

**Comment by kermitbbg** [comment]
LMAO how?

**Comment by pishangujeniya** [comment]
In the home page, there is sponsor button at the top.

**Comment by kermitbbg** [comment]
ok then?

**Comment by pishangujeniya** [comment]
Just enter, whatever amount you want to donate as per your wish.

**Comment by kermitbbg** [comment]
sorry to brust your bubble. i am 19 and i am broke and i am living under my parents shelter :((

**Comment by pishangujeniya** [comment]
This justifies the reason for visiting this repository.

**Comment by pishangujeniya** [comment]
Do not worry, Life is very Long, and everything will be fine.

**Comment by kermitbbg** [comment]
HI I AM HERE AGAIN. NEED HELP. AT THE STARTING ITSELF I AM BEING SHOWN THIS 
![N](https://user-images.githubusercontent.com/101860058/159149451-65d76f8d-29dc-4620-9ddf-bb5ee73f6984.JPG)

**Comment by kermitbbg** [comment]
AND THEN YESTERDAY I DID THE SAME EXACT SAME STEPS. I AM BEING SHOWN THIS.
![need help yo](https://user-images.githubusercontent.com/101860058/159149465-993762f4-5914-44bd-9ead-cf35fb926f3e.JPG)
