### ISSUE TITLE
Error 429 Too Many Requests

### ISSUE THREAD

**Issue by kermitbbg** [pishangujeniya/instagram-helper#71]
I DID EVERYTHING CORRECTLY BUT I AM BEING SHOWN THIS AGAIN AND AGAIN. I ALSO DELETED IT AND DOWNLOADED THE THING AGAIN AND LOGGED IN AND AGAIN STILL I AM BEING SHOWN THIS AGAIN AGAIN. PIC BELOW
![need help](https://user-images.githubusercontent.com/101860058/159112964-4a5452ca-8826-403e-aa2f-70980522ca59.JPG)

**Comment by pishangujeniya** [comment]
https://github.com/pishangujeniya/instagram-helper#-how-to-get-exported-all-messages

Do the mentioned above, and view it in here
 https://pishangujeniya.github.io/instagram-helper/InstagramHelperDataViewer.html

If any messages are there yet to be deleted then do the below

https://github.com/pishangujeniya/instagram-helper#-getting-too-often-try-again-tomorrow-error-or-429-response-code
