### ISSUE TITLE
Messages are not deleted, although it shows in the console.

### ISSUE THREAD

**Issue by Milozaki7** [pishangujeniya/instagram-helper#73]
I have followed all the steps as in the tutorial and also restarted the browser, have already gone through the issues but nothing really helped me.
When I run the code, the console says "All messages deleted.", but nothing has been deleted.
I'm guessing there was an update from Instagram the last 20 days but I really need help.
Thanks very much!
![Screenshot 2022-04-09 124356](https://user-images.githubusercontent.com/32218972/162568567-94355892-4d5c-4a24-8375-962f3c5fe066.png)

**Comment by pishangujeniya** [comment]
As you are passing 10, so it will be skipping the recent 10 messages, and you will not be having any more than 10 messages in the chat thread sent from your side, so it shows `All messages deleted`.

You can try  following everything from scratch with each step very strictly followed.

**Comment by pishangujeniya** [comment]
You can even try for confirmation
https://github.com/pishangujeniya/instagram-helper#-how-to-get-exported-all-messages

This will give you a file downloaded and which can be opened and viewed here https://pishangujeniya.github.io/instagram-helper/InstagramHelperDataViewer.html

If after loading that file, it doesn't show any messages from your side then definitely the script has worked fine, it's just you need to refresh your app or website page to clear the messages which are cached.

**Comment by Milozaki7** [comment]
> As you are passing 10, so it will be skipping the recent 10 messages, and you will not be having any more than 10 messages in the chat thread sent from your side, so it shows `All messages deleted`.
> 
> You can try following everything from scratch with each step very strictly followed.

I already tried to change the number 10 with lower ones or to remove it but nothing really changed.
I also exported the chat and viewed it with the json viewer but it still displays the last messages, I also refreshed my browser etc.

**Comment by pishangujeniya** [comment]
Try after some days, maybe Instagram has some limits to delete per day.
