### ISSUE TITLE
Error 429 

### ISSUE THREAD

**Issue by Sha3-sol** [pishangujeniya/instagram-helper#75]
Media are not deleted but I don't know why 
I already tried to put the value to 6500
Can you help me plz ? 
![image](https://user-images.githubusercontent.com/69468539/166708943-aa370932-4bed-4d7e-8cd4-8f974cee3595.png)

**Comment by pishangujeniya** [comment]
@Sha3-sol  Can you please refresh and check, media are really not deleted?
