### ISSUE TITLE
Does using this script notify the other user in any way?

### ISSUE THREAD

**Issue by waleedqq** [pishangujeniya/instagram-helper#76]
While using this script, to delete all messages + media I receive a message from someone asking me to stop spamming their phone. I was wondering does this script send any notifications to the user? Is there a certain behaviour like occurs? Do I need to stay in the particular chat during the whole deletion/unsending process?

**Comment by pishangujeniya** [comment]
- This script does not do anything else other than what you will do manually to delete (unsend) messages.
- Script does the same thing automatically which process you do manually.
- You should not do anything on that chat tab of browser while the script is running.
- You can minimise the that tab browser, and continue doing anything else in computer or in another window of browser. Just to make sure that the tab on which script is working you should not do anything else.
