### ISSUE TITLE
Temporary location for files stays empty

### ISSUE THREAD

**Issue by waleedqq** [pishangujeniya/instagram-helper#78]
**Describe the bug**
The temporary directory for Instagram Helper Files stays empty and then the InstagramHelperChromes does not open because it is pointing to an empty directory. 

**To Reproduce**
1. Go to InstagramHelperChrome.vbs script and run
2. Choose Temporary location for files (Documents)
3. Select directory to place Instagram Helper Shortcut (desktop)
4. Process completes, but then Instagram Helper Shortcut cannot find chrome.exe because Temoporary files location is empty. 

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Browser [e.g. chrome]

**Additional context**

**Comment by pishangujeniya** [comment]
1. Create Folder first
2. Then run `.vbs` file
3. Then select that folder
