### ISSUE TITLE
Access to fetch ... from origin instagram.com has been blocked by CORS policy

### ISSUE THREAD

**Issue by jayhxmo** [pishangujeniya/instagram-helper#79]
As of September 2022, the script is does not run and errors out.
Here's a screenshot of the console below:
<img width="1026" alt="CleanShot 2022-09-09 at 05 25 25@2x" src="https://user-images.githubusercontent.com/14072008/189245786-b78dccf2-279c-4ed8-8afd-3b7afa3e4d4c.png">

**Comment by pishangujeniya** [comment]
I have been busy these days, can someone help me.

**Comment by pishangujeniya** [comment]
You need to use the special chrome extension generated using the intial steps mentioned in the readme properly.

The script is working fine.
