### ISSUE TITLE
Uncaught TypeError: Cannot read

### ISSUE THREAD

**Issue by Devilishx** [pishangujeniya/instagram-helper#80]
**I have this issue and idk how to fix it :(** 
please guide me.
![2](https://user-images.githubusercontent.com/46275004/191220434-da8a9cf9-9379-4e4a-8805-2a8b5b5970d0.png)
![1](https://user-images.githubusercontent.com/46275004/191220445-1154c6a7-8121-4907-94ec-c209d1d9c948.png)

**Comment by pishangujeniya** [comment]
these are not the bugs, it happens, ignore it, you would be able to unsend the messages even with these errors.
