### ISSUE TITLE
Found a way to Run this on android

### ISSUE THREAD

**Issue by NivinCNC** [pishangujeniya/instagram-helper#83]
1) Download Kiwi Browser
2)Install This extension- CORS Unblock (https://chrome.google.com/webstore/detail/cors-unblock/lfhmikememgdcahcdlaciloancbhjino?hl=en)
And enable it (wont work if it was disabled)
3)Now login insta on kiwi in desktop mode

Now you can continue to
⁉ How to delete/unsend all messages? in readme.md

Note : you can access console in kiwi in developer tools
And also u can follow same method to do on pc also using this extension

Plz add this in your readme.md dev bro😁

Proof attached
![IMG_20221109_175710](https://user-images.githubusercontent.com/89772187/200830508-760dd93b-155b-44a5-b129-bf32103771dd.jpg)

**Comment by pishangujeniya** [comment]
@NivinCNC I was not aware of this. Thank You.
