### ISSUE TITLE
Call Function Missing (?)

### ISSUE THREAD

**Issue by MikeTemporary** [pishangujeniya/instagram-helper#9]
I’m trying to get the program to run through my iPad and when I input the code into the ‘Run Javascript’ module from the Shortcuts app, I get an error saying “The script must call the function ‘completion(result)` when finished.

**Comment by pishangujeniya** [comment]
Sorry, as of now I don't own an iPad or any Apple Devices, so I can't test on it. But, I can say firmly that it is working very well in Computer Browsers either on Linux, Windows, or macOS
