### ISSUE TITLE
Mac Issue Downloading Code

### ISSUE THREAD

**Issue by LeadingA5** [pishangujeniya/instagram-helper#92]
**Describe the bug**
Not able to download the code. I can copy the code, but there is no download button available. Tried to access a zip but was not able to. Please instruct how to download. Also, does this program work for Mac users. If not, how do I adapt it to work

**Comment by pishangujeniya** [comment]
@LeadingA5 check the pinned issues.

**Comment by LeadingA5** [comment]
Which one exactly? Don't see anything on this issue. Is it possible to
provide an answer directly? Thanks

**Comment by pishangujeniya** [comment]
@LeadingA5  https://github.com/pishangujeniya/instagram-helper/issues/22

**Comment by LeadingA5** [comment]
Stuck on the last step. Everything works except for when the code starts
running, it doesn't get past the "Getting Messages..." stage. After that I
get a bunch of errors. Any suggestions?

**Comment by LeadingA5** [comment]
Fixed that. However, now it says all messages deleted and nothing has been
deleted. I looked at number 73 but it still doesn't work. Any ideas?

**Comment by pishangujeniya** [comment]
Provide the screenshot of errors, so that I can detect what mistake you did.

**Comment by LeadingA5** [comment]
[image: image.png][image: image.png][image: image.png]

P.S, I do have the chrome extension active and running

**Comment by LeadingA5** [comment]
<img width="1066" alt="Screenshot 2023-04-19 at 12 15 22 PM" src="https://user-images.githubusercontent.com/131205414/233137008-a618f93d-2c33-48bf-9dba-83a4839a3331.png">

**Comment by pishangujeniya** [comment]
Please follow the steps properly, I can see that you are not following steps properly as per mentioned in the Readme.

Closing this issue.

No issues from our side.

**Comment by LeadingA5** [comment]
Tried everything and no success. It is not a CSP error, I make sure it's
active. I followed the ReadMe and tried to refresh constantly. Could you
send me your phone number or email and we can further discuss or call?
