### ISSUE TITLE
TRY AGAIN TOMORROW

### ISSUE THREAD

**Issue by idkasd1** [pishangujeniya/instagram-helper#94]
i tried everything to fix it , restart browser , signout and sign in again , delete the data , generate a new chrome app by .vbs file 
i did everything 
i hope that u can help me ASAP!

![image](https://user-images.githubusercontent.com/132169758/235324412-00ef71a4-ea88-4745-8a63-ab3e4a6fa3d7.png)

Thanks.

**Comment by pishangujeniya** [comment]
@idkasd1 May be you have deleted lot of messages today, they have rate limiting, so you need to do it tomorrow with fresh login.

**Comment by idkasd1** [comment]
i didnt use the tool for a week so i tried to use it but yea im still facing the same problem

**Comment by idkasd1** [comment]
Hey ,
i tried again today still showing me the same problem
Try Again Tomorrow 
:)

**Comment by idkasd1** [comment]
Bro r u still alive ;) @pishangujeniya

**Comment by idkasd1** [comment]
Okay , Im waitin

**Comment by pishangujeniya** [comment]
@idkasd1 I tried and tested, its working very perfect.
No issues from the script.
You may not be following the README perfectly.

Please follow README very properly.
