### ISSUE TITLE
WONT LET ME LOGIN TO INSTA THROUGH "SPECIAL CHROME"

### ISSUE THREAD

**Issue by meyend81** [pishangujeniya/instagram-helper#96]
I can login through chrome just fine, but whenever i try it through "InstagramHelperChrome"
after pressing on the "login" button, it just loads me back to the same page again and again....
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/44732779/235897358-dae14826-130c-4c44-ba23-3cec339f4b32.png">
anyone else having the same issue?!

**Comment by pishangujeniya** [comment]
Very weird issue, you try disabling CSP and then refresh and then login and again enable CSP and try it.

**Comment by pishangujeniya** [comment]
No reply from auther, so closing issue.
